### ISSUE TITLE
Cannot run a console for a release

### ISSUE THREAD

**Issue by purinkle** [thoughtbot/flightctl#5]
Whenever I run `flightctl console -e dev`, I get the following message.

> Error: No such file or directory (os error 2)

I'm not sure if I can provide any more context than this.

I'm using macOS Monterey 12.1 (21C52)

What do you need from me to help debug the issue?

**Comment by cpjmcquillan** [comment]
I've also been having this issue (running Monterey 12.1 on M1).

**Comment by jferris** [comment]
@purinkle @cpjmcquillan Can you please paste the full output, including the command?

**Comment by cpjmcquillan** [comment]
```
> bin/flightctl -e staging console

Logging in for AWS profile project
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-central-1.amazonaws.com/

Then enter the code:

****-****
Successully logged into Start URL: https://project.awsapps.com/start
Error: No such file or directory (os error 2)
```

Once I have authorised in the browser, I just get the single line of output (`Error: No such file or directory (os error 2)`) whatever command I run (console/config etc)

**Comment by ghost** [comment]
I am also having this issue

```bash
jaredt:project (main)$ bin/flightctl --version
flightctl 0.1.3
jaredt:project (main)$ bin/flightctl -e staging console
Error: No such file or directory (os error 2)
jaredt:project (main)$ bin/flightctl -e dev console
Error: No such file or directory (os error 2)
```

I'm using Ubuntu via WSL2.

I see the same error mentioned here https://github.com/thoughtbot/flightctl/issues/2 in case that pulls a thread.

**Comment by jferris** [comment]
@cpjmcquillan @jared-thoughtbot - Can you please pull in the application repository and try running again with `-d`? I've added more logging to hopefully figure out where it's becoming unhappy.

**Comment by ghost** [comment]
@jferris here's my output:

```bash
jaredt:project (main)$ bin/flightctl -d -e staging console
[DEBUG flightctl] Loaded configuration from /home/jaredt/projects/project/flightctl.yaml:
...
[INFO  flightctl::flightctl::authorize] Authorizing using AWS SSO
[DEBUG flightctl::flightctl::authorize] Authorization successful
[DEBUG flightctl::flightctl::context] Looking for context project-booking-staging
[DEBUG flightctl::flightctl::context] Checking Kubernetes credentials for project-booking-staging
[DEBUG flightctl::flightctl::kubectl] Running kubectl with ["config", "view", "--output", "jsonpath={.users[*].name}"]
Error: No such file or directory (os error 2)
```

**Comment by tjvc** [comment]
In case it helps with debugging, I had this same error message and was able to work around it by generating a kubeconfig.

**Comment by jferris** [comment]
@jared-thoughtbot Do you have kubectl installed? `which kubectl`

**Comment by ghost** [comment]
@jferris no, I don't have it installed. `which kubectl` returns nothing.

**Comment by jferris** [comment]
@jared-thoughtbot - Can you install `kubectl` via Homebrew/Aptitude/whatever and give it a shot? I think that's the issue. I can improve the error message here and potentially embed `kubectl` eventually, but it currently requires you to have the AWS CLI and kubectl installed locally.

**Comment by ghost** [comment]
@jferris I'm in! 😎 I [installed kubectl](https://kubernetes.io/docs/tasks/tools/) and then it worked like a charm!

Thanks for your help with this.

FYI @purinkle @cpjmcquillan
